# Generated by Django 3.2.5 on 2021-09-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('Sociedade', 'S'), ('Ciência', 'C'), ('Crime', 'CM'), ('Cultura', 'CL'), ('Economia', 'E'), ('Educação', 'ED'), ('Esporte', 'ES'), ('Política', 'P'), ('Saúde', 'S')], default='Sociedade', max_length=10)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.edicao')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.DecimalField(decimal_places=1, max_digits=1)),
                ('comentario', models.TextField(max_length=300)),
                ('data_publicação', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.edicao')),
            ],
        ),
    ]
